### ISSUE TITLE
CI tests fail

### ISSUE THREAD

**Issue by Hamza-Falih** [grp-attestoodle/moodle-tool_taskattestoodle#4]
CI tests fail at the "install moodle-plugin-ci" step.

The error output is : node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)

When I looked up in the internet, apparently the base image runs on ubuntu-18.04 and node v18.15.0 dropped support for Ubuntu 18 because it doesn't include a new enough version of gcc.

![CI tests fail](https://user-images.githubusercontent.com/34319005/224078928-e768a324-8feb-4a01-b844-ade201d9a1d7.PNG)

A possible solution would be to update the moodle-ci.yml to the latest version available on the moodlehq GitHub : [https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml](https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml)

**Comment by Hamza-Falih** [comment]
After updating the moodle-ci.yml file, the CI tests' installation has succeeded.

![CI tests installation success](https://user-images.githubusercontent.com/34319005/224082559-cf569e63-d106-4d46-8c3c-18632414e61d.PNG)


I will try to correct the Moodle Code Checker errors and warnings now.

**Comment by dcadiou** [comment]
Bien joué.
